const { marked } = require('marked');
const sanitizeHtml = require('sanitize-html');

exports.buildReportHtml = (target, scanOutput, aiSummary) => {
  const escapeText = (str) => {
    if (typeof str !== 'string') return '';
    return str
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#x27;')
      .replace(/\//g, '&#x2F;');
  };

  const safeTarget = escapeText(target || 'N/A');
  const safeScanOutput = escapeText(scanOutput || '');

  const rawSummaryMd = typeof aiSummary === 'string' ? aiSummary : '';
  const summaryHtml = marked.parse(rawSummaryMd || '');
  const safeAiSummary = sanitizeHtml(summaryHtml, {
    allowedTags: sanitizeHtml.defaults.allowedTags.concat(['h1','h2','h3','h4','h5','h6','img','span']),
    allowedAttributes: {
      a: ['href', 'name', 'target', 'rel'],
      img: ['src', 'alt', 'title'],
      '*': ['class']
    },
    allowedSchemes: ['http', 'https', 'mailto']
  });

  const currentDate = new Date().toUTCString();

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Nmap Scan Report - ${safeTarget}</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body { 
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
      line-height: 1.6;
      color: #333;
      background-color: #f8f9fa;
    }
    
    .container { 
      max-width: 1000px; 
      margin: 0 auto;
      background: white;
      box-shadow: 0 0 20px rgba(0,0,0,0.1);
      min-height: 100vh;
    }
    
    .header {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 2rem;
      text-align: center;
    }
    
    .header h1 {
      font-size: 2.5rem;
      margin-bottom: 0.5rem;
      font-weight: 300;
    }
    
    .header .subtitle {
      font-size: 1.1rem;
      opacity: 0.9;
    }
    
    .content {
      padding: 2rem;
    }
    
    .info-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 1rem;
      margin-bottom: 2rem;
    }
    
    .info-card {
      background: #f8f9fa;
      padding: 1rem;
      border-radius: 8px;
      border-left: 4px solid #667eea;
    }
    
    .info-card h3 {
      color: #667eea;
      margin-bottom: 0.5rem;
      font-size: 0.9rem;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    
    .info-card p {
      font-size: 1.1rem;
      font-weight: 500;
    }
    
    .section {
      margin-bottom: 2rem;
    }
    
    .section h2 {
      color: #333;
      margin-bottom: 1rem;
      padding-bottom: 0.5rem;
      border-bottom: 2px solid #667eea;
      font-size: 1.5rem;
    }
    
    .summary-content {
      background: #e8f4fd;
      border: 1px solid #bee5eb;
      border-radius: 8px;
      padding: 1.5rem;
      margin-bottom: 1rem;
    }
    
    .scan-output {
      background: #f8f9fa;
      border: 1px solid #dee2e6;
      border-radius: 8px;
      padding: 1.5rem;
      font-family: 'Courier New', monospace;
      font-size: 0.9rem;
      line-height: 1.4;
      white-space: pre-wrap;
      word-wrap: break-word;
      max-height: 600px;
      overflow-y: auto;
    }
    
    .footer {
      background: #f8f9fa;
      padding: 1rem 2rem;
      text-align: center;
      color: #6c757d;
      border-top: 1px solid #dee2e6;
    }
    
    .timestamp {
      font-size: 0.9rem;
      color: #6c757d;
    }
    
    @media print {
      body { background: white; }
      .container { box-shadow: none; }
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>Network Security Scan Report</h1>
      <p class="subtitle">Comprehensive Network Analysis with AI-Powered Insights</p>
    </div>
    
    <div class="content">
      <div class="info-grid">
        <div class="info-card">
          <h3>Target</h3>
          <p>${safeTarget}</p>
        </div>
        <div class="info-card">
          <h3>Scan Date</h3>
          <p>${currentDate}</p>
        </div>
        <div class="info-card">
          <h3>Report Generated</h3>
          <p>${new Date().toLocaleString()}</p>
        </div>
      </div>

      <div class="section">
        <h2>🔍 AI-Powered Analysis</h2>
        <div class="summary-content">
          ${safeAiSummary}
        </div>
      </div>

      <div class="section">
        <h2>📊 Raw Scan Output</h2>
        <div class="scan-output">${safeScanOutput}</div>
      </div>
    </div>
    
    <div class="footer">
      <p class="timestamp">Report generated on ${currentDate}</p>
      <p>Generated by NetScan AI - Advanced Network Security Analysis</p>
    </div>
  </div>
</body>
</html>
`;
};
